# docker-compose.yml
version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "5173:5173" # Port par défaut de Vite en dev
    environment:
      - VITE_API_URL=http://localhost:8080
      - VITE_KEYCLOAK_URL=http://localhost:8180
      - VITE_KEYCLOAK_REALM=medical-cabinet
      - VITE_KEYCLOAK_CLIENT_ID=medical-frontend
    volumes:
      - ./src:/app/src
    depends_on:
      - mongodb
      - keycloak

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "5000:5000"
    volumes:
      - ./src:/app/src

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d/
    environment:
      - MONGO_INITDB_DATABASE=medical_cabinet
    command: [ "--noauth" ]
    restart: always

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=password
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://postgres:5432/keycloak
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=password
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=password
      - KC_REALM_IMPORT=/opt/keycloak/data/import/realm-medical.json
    ports:
      - "8180:8080"
    volumes:
      - ./keycloak:/opt/keycloak/data/import
      - ./keycloak/keycloak.conf:/opt/keycloak/conf/keycloak.conf
    command: [ "start-dev", "--import-realm" ]
    depends_on:
      - postgres

  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "keycloak" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mongodb_data:
  postgres_data:
