# Dockerfile.frontend
FROM node:18

# Set the working directory
WORKDIR /app

# Copy only the package files to take advantage of Docker cache
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the frontend code
COPY ./src /app/src
COPY ./public /app/public

# Expose the Vite dev server port
EXPOSE 5173

# Run the frontend server
CMD ["npm", "run", "dev"]
