# Dockerfile.backend
FROM node:18

# Set the working directory
WORKDIR /app

# Copy only the package files to take advantage of Docker cache
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the backend code
COPY ./backend /app

# Expose the backend API port
EXPOSE 3000

# Run the backend server
CMD ["node", "app.js"]
